chore:
  - any: ['*']
    all: ['!packages/*', '!packages/**/*']

'packages:builders':
  - packages/builders/*
  - packages/builders/**/*

'packages:collection':
  - packages/collection/*
  - packages/collection/**/*

'packages:discord.js':
  - packages/discord.js/*
  - packages/discord.js/**/*

'packages:docgen':
  - packages/docgen/*
  - packages/docgen/**/*

'packages:proxy':
  - packages/proxy/*
  - packages/proxy/**/*

'packages:rest':
  - packages/rest/*
  - packages/rest/**/*

'packages:voice':
  - packages/voice/*
  - packages/voice/**/*

'packages:website':
  - packages/website/*
  - packages/website/**/*

'packages:ws':
  - packages/ws/*
  - packages/ws/**/*
