packages:builders:
  - packages/builders/*
  - packages/builders/**/*
packages:collection:
  - packages/collection/*
  - packages/collection/**/*
packages:discord.js:
  - packages/discord.js/*
  - packages/discord.js/**/*
packages:docgen:
  - packages/docgen/*
  - packages/docgen/**/*
packages:guide:
  - packages/guide/*
  - packages/guide/**/*
packages:proxy:
  - packages/proxy/*
  - packages/proxy/**/*
packages:proxy-container:
  - packages/proxy-container/*
  - packages/proxy-container/**/*
packages:rest:
  - packages/rest/*
  - packages/rest/**/*
packages:util:
  - packages/util/*
  - packages/util/**/*
packages:voice:
  - packages/voice/*
  - packages/voice/**/*
packages:website:
  - packages/website/*
  - packages/website/**/*
packages/web-components:
  - packages:web-components/*
  - packages:web-components/**/*
packages:ws:
  - packages/ws/*
  - packages/ws/**/*
