name: Publish dev docker images
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  docker-publish:
    name: Docker publish
    runs-on: ubuntu-latest
    if: github.repository_owner == 'discordjs'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: ./packages/actions/src/yarnCache

      - name: Build dependencies
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the image
        run: yarn docker build @discordjs/proxy-container -t discordjs/proxy:latest

      - name: Push image to DockerHub
        run: docker push discordjs/proxy:latest
