name: Publish dev
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  npm-publish:
    name: npm publish
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: '@discordjs/builders'
            folder: 'builders'
          - package: '@discordjs/collection'
            folder: 'collection'
          - package: 'discord.js'
            folder: 'discord.js'
          - package: '@discordjs/proxy'
            folder: 'proxy'
          - package: '@discordjs/rest'
            folder: 'rest'
          - package: '@discordjs/voice'
            folder: 'voice'
          - package: '@discordjs/ws'
            folder: 'ws'
    runs-on: ubuntu-latest
    if: github.repository_owner == 'discordjs'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Build dependencies
        run: yarn build

      - name: Publish package
        run: |
          yarn workspace ${{ matrix.package }} release --preid "dev.$(date +%s)-$(git rev-parse --short HEAD)"
          yarn workspace ${{ matrix.package }} npm publish --tag dev || true
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
