name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Turbo cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install dependencies
        run: yarn --immutable

      - name: ESLint
        run: yarn lint --cache-dir=".turbo"

      - name: Tests
        run: yarn test

      - name: Upload Coverage
        uses: ./packages/actions/src/uploadCoverage
        if: github.repository_owner == 'discordjs'

      - name: Build
        run: yarn build --cache-dir=".turbo"
